displayName=Leechfin Fishing
author=Andrew Scherer
description=Highlighting for leechfin fishing.
tags=leechfin,fishing,highlight,vampyrium
version=1.0.1
plugins=com.leechfinfishing.LeechfinFishingPlugin
build=standard